In [16]:
import tensorflow as tf
import numpy as np

# /Users/hieutran/lab/unicon-ids/data/can-ml/preprocessed/all_features/TFRecord_w32_s16/2
tfrecord_file_path = '../data/can-ml/preprocessed/all_features_v2/TFRecord_w32_s16/2/train/0.tfrec'

def parse_tfrecord_fn(example):
    feature_description = {
        'id_seq': tf.io.FixedLenFeature([32, 32], tf.int64),
        'data_seq': tf.io.FixedLenFeature([32, 32], tf.int64),
        'timestamp': tf.io.FixedLenFeature([32, 32], tf.float32),
        'label': tf.io.FixedLenFeature([1], tf.int64)
    }
    return tf.io.parse_single_example(example, feature_description)

# Tạo dataset từ TFRecord file
raw_dataset = tf.data.TFRecordDataset(tfrecord_file_path)
parsed_dataset = raw_dataset.map(parse_tfrecord_fn)

# Hiển thị toàn bộ nội dung của timestamp
for i, parsed_record in enumerate(parsed_dataset.take(5)):  # Lấy 5 bản ghi đầu tiên
    timestamp_array = parsed_record['data_seq'].numpy()  # Chuyển sang NumPy array
    print(f"Record {i+1} - Timestamp data:")
    print(np.array2string(timestamp_array, threshold=np.inf))  # In toàn bộ dữ liệu
    print("\n" + "="*50 + "\n")


Record 1 - Timestamp data:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 1]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 0 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0]
 [0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 0]
 [1 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 1 1 0 1 0 0 0 0 0 1 0 0 0]
 [0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 1 1 1 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0